import {useEffect,useRef,useState} from 'react';
import {motion,useScroll,useTransform} from 'framer-motion';
import {ArrowDown,ArrowLeft} from 'lucide-react';
interface Props{onBack:()=>void;isDark?:boolean}
const chapters=[
 {eyebrow:'01 — The question',title:'What if care felt like desire?',body:'We began with a refusal: performance should not require compromise. Not for your skin. Not for the room you enter. Not for the world you leave behind.',color:'#6f4332',image:`${import.meta.env.BASE_URL}aura-noir.png`},
 {eyebrow:'02 — The formula',title:'Nothing hidden. Everything intentional.',body:'Botanical materials and fine-fragrance craft work with the body. Every ingredient earns its place; every note is composed with restraint.',color:'#354b3c',image:`${import.meta.env.BASE_URL}aura-forest.png`},
 {eyebrow:'03 — The object',title:'Designed to remain.',body:'A weighty refillable vessel turns a disposable routine into a lasting object. Keep the bottle. Replace only what is used.',color:'#766349',image:`${import.meta.env.BASE_URL}aura-atelier.png`},
 {eyebrow:'04 — Your chapter',title:'A ritual that becomes yours.',body:'Morning clarity. Evening calm. A familiar object in the palm. Aura is less about covering who you are, and more about arriving fully.',color:'#535a63',image:`${import.meta.env.BASE_URL}aura-silver.png`},
];
export default function StorytellingConcept({onBack}:Props){const root=useRef<HTMLDivElement>(null);const[active,setActive]=useState(0);const{scrollYProgress}=useScroll({target:root,offset:['start start','end end']});const progress=useTransform(scrollYProgress,[0,1],['0%','100%']);useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setActive(Number((e.target as HTMLElement).dataset.index))}),{threshold:.55});document.querySelectorAll('[data-story]').forEach(x=>o.observe(x));return()=>o.disconnect()},[]);return <div ref={root} className="bg-[#090a0c] text-white">
 <header className="fixed inset-x-0 top-0 z-50 bg-black/15 backdrop-blur"><div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 lg:px-10"><button onClick={onBack} className="flex items-center gap-2 text-sm text-white/70"><ArrowLeft className="h-4 w-4"/> Concepts</button><span className="font-serif text-xl tracking-[.24em]">AURA STORIES</span><span className="text-xs text-white/45">0{active+1} / 04</span></div><div className="h-px bg-white/10"><motion.div style={{width:progress}} className="h-full bg-[#d7bf91]"/></div></header>
 <main><section className="relative flex min-h-screen items-end overflow-hidden px-5 pb-16 pt-28 lg:px-10 lg:pb-24"><img src={`${import.meta.env.BASE_URL}aura-collection.png`} alt="Aura collection" className="absolute inset-0 h-full w-full object-cover opacity-70"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/10 to-black/35"/><div className="relative mx-auto w-full max-w-[1500px]"><p className="text-xs uppercase tracking-[.3em] text-[#d7bf91]">An object with a point of view</p><h1 className="mt-5 max-w-5xl text-6xl leading-[.94] tracking-[-.05em] sm:text-7xl lg:text-[8.5rem]">The story begins<br/><span className="font-serif italic text-white/65">under the surface.</span></h1><div className="mt-10 flex items-center gap-3 text-sm text-white/55"><ArrowDown className="h-4 w-4 animate-bounce"/> Scroll to enter</div></div></section>
 {chapters.map((c,i)=><section key={c.title} data-story data-index={i} className="sticky top-0 flex min-h-screen items-center overflow-hidden px-5 py-24 lg:px-10" style={{backgroundColor:c.color}}><motion.img initial={{scale:1.12}} whileInView={{scale:1}} transition={{duration:1.5}} src={c.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-25 blur-sm"/><div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/35 to-black/5"/><div className="relative mx-auto grid w-full max-w-[1500px] items-center gap-14 lg:grid-cols-2"><motion.div initial={{opacity:0,y:45}} whileInView={{opacity:1,y:0}} viewport={{amount:.5}}><p className="text-xs uppercase tracking-[.3em] text-white/60">{c.eyebrow}</p><h2 className="mt-6 text-5xl leading-[.98] tracking-[-.045em] sm:text-7xl lg:text-8xl">{c.title}</h2><p className="mt-8 max-w-xl text-lg leading-relaxed text-white/72 sm:text-xl">{c.body}</p></motion.div><motion.div initial={{x:90,rotate:5,scale:.9,opacity:0}} whileInView={{x:0,rotate:0,scale:1,opacity:1}} viewport={{amount:.5}} transition={{duration:.9}} className="mx-auto w-full max-w-xl overflow-hidden rounded-[2.5rem] border border-white/20 shadow-2xl"><img src={c.image} alt={`Aura chapter ${i+1}`} className="aspect-[4/5] w-full object-cover"/></motion.div></div></section>)}
 <section className="relative grid min-h-screen place-items-center overflow-hidden px-5 text-center"><img src={`${import.meta.env.BASE_URL}aura-collection.png`} alt="" className="absolute inset-0 h-full w-full object-cover opacity-45"/><div className="absolute inset-0 bg-black/50"/><div className="relative"><p className="text-xs uppercase tracking-[.3em] text-[#d7bf91]">Continue the story</p><h2 className="mt-5 text-6xl tracking-[-.05em] sm:text-8xl">Choose your Aura.</h2><button className="mt-9 rounded-full bg-white px-8 py-4 text-black">Explore the collection</button></div></section></main>
 </div>}
