import { useEffect,useState } from 'react';
import { AnimatePresence,motion } from 'framer-motion';
import { ArrowLeft,ArrowRight,Check,Heart,Search,ShoppingBag,Star,X } from 'lucide-react';
interface Props{onBack:()=>void;isDark?:boolean}
const products=[
 {id:1,name:'Aura Noir',notes:'Bergamot · Black tea',price:142,image:`${import.meta.env.BASE_URL}aura-noir.png`},
 {id:2,name:'Aura Atelier',notes:'Amber · Sandalwood',price:168,image:`${import.meta.env.BASE_URL}aura-atelier.png`},
 {id:3,name:'Aura Forest',notes:'Hinoki · Vetiver',price:154,image:`${import.meta.env.BASE_URL}aura-forest.png`},
 {id:4,name:'Aura Silver',notes:'Salt · White cedar',price:148,image:`${import.meta.env.BASE_URL}aura-silver.png`},
];
type Product=typeof products[number];
export default function StorefrontConcept({onBack,isDark}:Props){
 const [active,setActive]=useState(0),[direction,setDirection]=useState(1),[auto,setAuto]=useState(true),[quick,setQuick]=useState<Product|null>(null),[cart,setCart]=useState<string[]>([]);const p=products[active];
 const move=(d:number)=>{setDirection(d);setAuto(false);setActive(i=>(i+d+products.length)%products.length)};
 useEffect(()=>{if(!auto)return;const id=setInterval(()=>{setDirection(1);setActive(i=>(i+1)%products.length)},4800);return()=>clearInterval(id)},[auto]);
 return <div className={`min-h-screen ${isDark?'bg-[#10110f] text-[#f2eee5]':'bg-[#eee9df] text-[#181914]'}`}>
  <header className={`fixed inset-x-0 top-0 z-50 border-b backdrop-blur-xl ${isDark?'border-white/10 bg-[#10110f]/85':'border-black/10 bg-[#eee9df]/85'}`}><div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 lg:px-10"><button onClick={onBack} className="flex items-center gap-2 text-sm"><ArrowLeft className="h-4 w-4"/> Concepts</button><span className="font-semibold tracking-[.28em]">AURA PARFUMS</span><div className="flex gap-5"><button aria-label="Search"><Search className="h-5 w-5"/></button><button className="relative" aria-label="Bag"><ShoppingBag className="h-5 w-5"/>{cart.length>0&&<span className="absolute -right-2 -top-2 grid h-4 w-4 place-items-center rounded-full bg-orange-600 text-[10px] text-white">{cart.length}</span>}</button></div></div></header>
  <main className="pt-20">
   <section className="relative min-h-[calc(100vh-5rem)] overflow-hidden bg-[#0d0e0c] text-white"><AnimatePresence mode="wait"><motion.div key={p.id} initial={{opacity:0}} animate={{opacity:.32}} exit={{opacity:0}} className="absolute inset-0 scale-110 bg-cover bg-center blur-3xl" style={{backgroundImage:`url(${p.image})`}}/></AnimatePresence><div className="absolute inset-0 bg-black/55"/><div className="relative mx-auto grid min-h-[calc(100vh-5rem)] max-w-[1500px] items-center gap-12 px-5 py-14 lg:grid-cols-[.72fr_1.28fr] lg:px-10"><div><p className="text-xs uppercase tracking-[.3em] text-[#d7bf91]">The signature shelf</p><AnimatePresence mode="wait" custom={direction}><motion.div key={p.id} custom={direction} initial={{opacity:0,x:direction*35}} animate={{opacity:1,x:0}} exit={{opacity:0,x:direction*-35}}><h1 className="mt-5 text-6xl tracking-[-.055em] sm:text-7xl">{p.name}</h1><p className="mt-3 text-xl text-white/55">{p.notes}</p><div className="mt-5 flex items-center gap-2 text-sm text-white/70"><Star className="h-4 w-4 fill-current text-amber-300"/> 4.9 · 240 reviews</div><p className="mt-7 text-3xl">${p.price}</p></motion.div></AnimatePresence><div className="mt-8 flex gap-3"><button onClick={()=>setCart(c=>[...c,p.name])} className="rounded-full bg-white px-7 py-3 font-medium text-black">Add to bag</button><button onClick={()=>setQuick(p)} className="rounded-full border border-white/25 px-7 py-3">Quick view</button></div></div><div className="relative flex min-h-[570px] items-center justify-center"><AnimatePresence mode="popLayout" custom={direction}><motion.button key={p.id} custom={direction} initial={{opacity:0,x:direction*220,rotateY:direction*20,scale:.8}} animate={{opacity:1,x:0,rotateY:0,scale:1}} exit={{opacity:0,x:direction*-220,rotateY:direction*-20,scale:.8}} transition={{type:'spring',stiffness:110,damping:21}} onClick={()=>setQuick(p)} className="absolute overflow-hidden rounded-[2rem] shadow-2xl" aria-label={`Quick view ${p.name}`}><img src={p.image} alt={p.name} className="h-[540px] w-[400px] object-cover"/></motion.button></AnimatePresence><button onClick={()=>move(-1)} className="absolute left-0 z-20 rounded-full border border-white/25 bg-black/20 p-4 backdrop-blur" aria-label="Previous"><ArrowLeft/></button><button onClick={()=>move(1)} className="absolute right-0 z-20 rounded-full border border-white/25 bg-black/20 p-4 backdrop-blur" aria-label="Next"><ArrowRight/></button></div></div><div className="absolute bottom-5 left-1/2 flex -translate-x-1/2 gap-2">{products.map((x,i)=><button key={x.id} onClick={()=>{setDirection(i>active?1:-1);setActive(i);setAuto(false)}} className={`h-1 rounded-full transition-all ${i===active?'w-10 bg-white':'w-3 bg-white/25'}`} aria-label={`Go to ${x.name}`}/>)}</div></section>
   <section className="mx-auto max-w-[1500px] px-5 py-24 lg:px-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[.25em] opacity-50">The collection</p><h2 className="mt-3 text-5xl tracking-[-.04em]">Find your atmosphere.</h2></div><p className="max-w-sm opacity-55">Four compositions. Natural materials, lasting concentration, and a refillable object designed for your shelf.</p></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map(item=><article key={item.id}><button onClick={()=>setQuick(item)} className="group relative aspect-[4/5] w-full overflow-hidden rounded-[1.8rem] bg-black"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><Heart className="absolute right-5 top-5 text-white"/></button><div className="flex justify-between py-5"><div><h3 className="text-lg font-medium">{item.name}</h3><p className="text-sm opacity-50">{item.notes}</p><p className="mt-2">${item.price}</p></div><button onClick={()=>setCart(c=>[...c,item.name])} className="self-start rounded-full border border-current/20 p-3" aria-label={`Add ${item.name}`}><ShoppingBag className="h-4 w-4"/></button></div></article>)}</div></section>
   <section className="bg-[#1a1b17] px-5 py-24 text-white"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-3">{[['01','Complimentary discovery set'],['02','Refillable by design'],['03','Delivered on your rhythm']].map(x=><div key={x[0]} className="border-t border-white/20 pt-6"><span className="text-xs text-[#d7bf91]">{x[0]}</span><h3 className="mt-5 text-2xl">{x[1]}</h3><p className="mt-3 text-white/50">A considered service from first impression to every refill after.</p></div>)}</div></section>
  </main>
  {quick&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/70 p-4 backdrop-blur" role="dialog" aria-modal="true"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} className="relative grid w-full max-w-4xl overflow-hidden rounded-[2rem] bg-[#eee9df] text-[#181914] sm:grid-cols-2"><button onClick={()=>setQuick(null)} className="absolute right-5 top-5 z-10 rounded-full bg-white/70 p-2" aria-label="Close"><X/></button><img src={quick.image} alt={quick.name} className="h-full min-h-[480px] w-full object-cover"/><div className="self-center p-9"><p className="text-xs uppercase tracking-[.25em]">Eau de parfum · 75ml</p><h2 className="mt-4 text-5xl">{quick.name}</h2><p className="mt-3 opacity-50">{quick.notes}</p><p className="mt-7 text-2xl">${quick.price}</p><ul className="mt-8 space-y-3 text-sm">{['Complimentary discovery vial','Refillable glass and metal vessel','Free delivery and returns'].map(x=><li key={x} className="flex gap-2"><Check className="h-4 w-4"/>{x}</li>)}</ul><button onClick={()=>{setCart(c=>[...c,quick.name]);setQuick(null)}} className="mt-9 w-full rounded-full bg-black py-4 text-white">Add to bag</button></div></motion.div></div>}
 </div>
}
