import { useEffect,useRef,useState } from 'react';
import { AnimatePresence,motion } from 'framer-motion';
import { ArrowLeft,ArrowRight,Check,Expand,Hand,Pause,Play,RotateCcw,ShoppingBag } from 'lucide-react';
import * as THREE from 'three';
interface Props{onBack:()=>void;isDark?:boolean}
const variants=[
 {name:'Aura Noir',notes:'Bergamot · Black tea',price:142,image:`${import.meta.env.BASE_URL}aura-noir.png`,body:0x111111,accent:0xb88a4f},
 {name:'Aura Atelier',notes:'Amber · Sandalwood',price:168,image:`${import.meta.env.BASE_URL}aura-atelier.png`,body:0xb29668,accent:0xf0dcae},
 {name:'Aura Forest',notes:'Hinoki · Vetiver',price:154,image:`${import.meta.env.BASE_URL}aura-forest.png`,body:0x14372a,accent:0xb28b52},
 {name:'Aura Silver',notes:'Salt · White cedar',price:148,image:`${import.meta.env.BASE_URL}aura-silver.png`,body:0x9da0a0,accent:0xe7e3d8},
];
export default function ThreeDConcept({onBack}:Props){
 const mount=useRef<HTMLDivElement>(null),rotation=useRef({x:0,y:0});const [active,setActive]=useState(0),[auto,setAuto]=useState(true),[selected,setSelected]=useState(false),[hint,setHint]=useState(true);const v=variants[active];
 useEffect(()=>{const el=mount.current;if(!el)return;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,.2,5.6);const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;el.appendChild(renderer.domElement);
  const group=new THREE.Group();const glass=new THREE.MeshPhysicalMaterial({color:v.body,metalness:.2,roughness:.12,transmission:.18,thickness:1,clearcoat:1,clearcoatRoughness:.08});const gold=new THREE.MeshPhysicalMaterial({color:v.accent,metalness:.92,roughness:.16,clearcoat:.8});
  const bottle=new THREE.Mesh(new THREE.BoxGeometry(2.05,2.65,.92,8,8,8),glass);bottle.position.y=-.25;bottle.castShadow=true;group.add(bottle);const shoulders=new THREE.Mesh(new THREE.CylinderGeometry(.72,1.02,.45,48),gold);shoulders.position.y=1.18;group.add(shoulders);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,.48,48),gold);neck.position.y=1.55;group.add(neck);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.66,.66,.62,48),glass);cap.position.y=2.05;group.add(cap);const plate=new THREE.Mesh(new THREE.BoxGeometry(1.28,.42,.035),gold);plate.position.set(0,.05,.48);group.add(plate);scene.add(group);
  const floor=new THREE.Mesh(new THREE.CircleGeometry(2.2,64),new THREE.MeshPhysicalMaterial({color:0x111111,metalness:.65,roughness:.22,transparent:true,opacity:.72}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.63;floor.receiveShadow=true;scene.add(floor);
  scene.add(new THREE.HemisphereLight(0xf5ead8,0x111018,1.5));const key=new THREE.SpotLight(v.accent,85,12,Math.PI/5,.5,1);key.position.set(3.5,5,4);key.castShadow=true;scene.add(key);const rim=new THREE.PointLight(0x8bbcff,22,9);rim.position.set(-3,1,-2);scene.add(rim);
  const pg=new THREE.BufferGeometry(),pos=new Float32Array(600);for(let i=0;i<600;i++)pos[i]=(Math.random()-.5)*11;pg.setAttribute('position',new THREE.BufferAttribute(pos,3));const points=new THREE.Points(pg,new THREE.PointsMaterial({color:v.accent,size:.018,transparent:true,opacity:.4}));scene.add(points);
  let drag=false,px=0,py=0,raf=0;const resize=()=>{const w=el.clientWidth,h=el.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)};const down=(e:PointerEvent)=>{drag=true;px=e.clientX;py=e.clientY;setAuto(false);setHint(false);renderer.domElement.setPointerCapture(e.pointerId)};const move=(e:PointerEvent)=>{if(!drag)return;rotation.current.y+=(e.clientX-px)*.008;rotation.current.x=Math.max(-.4,Math.min(.4,rotation.current.x+(e.clientY-py)*.006));px=e.clientX;py=e.clientY};const up=()=>drag=false;const wheel=(e:WheelEvent)=>{e.preventDefault();camera.position.z=Math.max(4,Math.min(7,camera.position.z+e.deltaY*.002))};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('wheel',wheel,{passive:false});window.addEventListener('resize',resize);resize();const tick=()=>{raf=requestAnimationFrame(tick);if(auto)rotation.current.y+=.003;group.rotation.y+=(rotation.current.y-group.rotation.y)*.12;group.rotation.x+=(rotation.current.x-group.rotation.x)*.12;group.position.y=Math.sin(performance.now()*.001)*.035;points.rotation.y+=.0003;renderer.render(scene,camera)};tick();return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);renderer.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(o.material as THREE.Material).dispose()}});el.innerHTML=''}},[active,auto,v]);
 const change=(d:number)=>{setActive(i=>(i+d+variants.length)%variants.length);setSelected(false)};
 return <div className="min-h-screen overflow-x-hidden bg-[#070808] text-white">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-black/25 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 lg:px-10"><button onClick={onBack} className="flex items-center gap-2 text-sm text-white/65"><ArrowLeft className="h-4 w-4"/> Concepts</button><span className="font-semibold tracking-[.3em]">AURA SPACE</span><button aria-label="Bag"><ShoppingBag className="h-5 w-5"/></button></div></header>
  <main>
   <section className="relative min-h-screen overflow-hidden pt-20"><AnimatePresence mode="wait"><motion.img key={v.image} src={v.image} alt="" initial={{opacity:0,scale:1.08}} animate={{opacity:.32,scale:1}} exit={{opacity:0}} transition={{duration:.9}} className="absolute inset-0 h-full w-full object-cover blur-2xl"/></AnimatePresence><div className="absolute inset-0 bg-[radial-gradient(circle_at_65%_45%,transparent,rgba(0,0,0,.82)_68%)]"/>
    <div className="relative mx-auto grid min-h-[calc(100vh-5rem)] max-w-[1500px] items-center px-5 lg:grid-cols-[.7fr_1.3fr] lg:px-10"><motion.div initial={{opacity:0,x:-25}} animate={{opacity:1,x:0}} className="z-10 py-12"><p className="text-xs uppercase tracking-[.32em] text-amber-300">Interactive fragrance object</p><AnimatePresence mode="wait"><motion.div key={v.name} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-16}}><h1 className="mt-5 text-6xl tracking-[-.055em] sm:text-7xl">{v.name}</h1><p className="mt-3 text-xl text-white/50">{v.notes}</p><p className="mt-8 text-3xl">${v.price}</p></motion.div></AnimatePresence><div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>setSelected(true)} className="rounded-full bg-white px-7 py-3 font-medium text-black">{selected?<span className="flex items-center gap-2"><Check className="h-4 w-4"/> Selected</span>:'Choose this fragrance'}</button><button onClick={()=>setAuto(a=>!a)} className="flex items-center gap-2 rounded-full border border-white/20 px-6 py-3">{auto?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}{auto?'Pause motion':'Resume motion'}</button></div><div className="mt-10 flex gap-3">{variants.map((item,i)=><button key={item.name} onClick={()=>setActive(i)} className={`h-16 w-14 overflow-hidden rounded-xl border ${active===i?'border-white':'border-white/15 opacity-50 hover:opacity-100'}`} aria-label={`View ${item.name}`}><img src={item.image} alt="" className="h-full w-full object-cover"/></button>)}</div></motion.div>
     <div className="relative min-h-[620px] lg:min-h-[calc(100vh-5rem)]"><div ref={mount} className="absolute inset-0 touch-none" aria-label={`Interactive 3D model of ${v.name}`}/>{hint&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="pointer-events-none absolute bottom-24 left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-full border border-white/15 bg-black/35 px-5 py-3 text-sm text-white/65 backdrop-blur"><Hand className="h-4 w-4"/> Drag to hold · Scroll to approach</motion.div>}<button onClick={()=>change(-1)} className="absolute left-0 top-1/2 rounded-full border border-white/20 bg-black/30 p-3 backdrop-blur" aria-label="Previous fragrance"><ArrowLeft/></button><button onClick={()=>change(1)} className="absolute right-0 top-1/2 rounded-full border border-white/20 bg-black/30 p-3 backdrop-blur" aria-label="Next fragrance"><ArrowRight/></button></div>
    </div>
   </section>
   <section className="border-t border-white/10 px-5 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-[1500px]"><p className="text-xs uppercase tracking-[.3em] text-amber-300">Explore without distance</p><h2 className="mt-5 max-w-5xl text-5xl tracking-[-.05em] sm:text-7xl">A digital encounter<br/><span className="font-serif italic text-white/45">with physical presence.</span></h2><div className="mt-16 grid gap-6 md:grid-cols-3">{[[RotateCcw,'Orbit every surface','Inspect the silhouette, materials and reflections from every angle.'],[Expand,'Move through space','Use the wheel or trackpad to control distance and perspective.'],[Hand,'Made for touch','The same physical interaction translates naturally to mobile gestures.']].map(([Icon,title,body])=><article key={String(title)} className="rounded-[2rem] border border-white/10 bg-white/[.035] p-8 transition duration-500 hover:-translate-y-2 hover:border-amber-300/35"><Icon className="h-7 w-7 text-amber-300"/><h3 className="mt-16 text-2xl">{title as string}</h3><p className="mt-4 leading-relaxed text-white/45">{body as string}</p></article>)}</div></div></section>
   <section className="relative min-h-[70vh] overflow-hidden"><img src={v.image} alt={`${v.name} campaign`} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/85 to-transparent"/><div className="relative mx-auto flex min-h-[70vh] max-w-[1500px] items-center px-5 lg:px-10"><div className="max-w-xl"><p className="text-xs uppercase tracking-[.3em] text-amber-300">From space to skin</p><h2 className="mt-5 text-6xl tracking-[-.05em]">Now make it yours.</h2><button className="mt-8 rounded-full bg-white px-7 py-3 text-black">Discover {v.name}</button></div></div></section>
  </main>
 </div>
}
